name: handy_help_app
description: A premium service booking platform connecting users with verified service providers.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management and architecture
  provider: ^6.1.1
  get_it: ^7.6.0
  get: ^4.6.5

  # UI and animations
  flutter_animate: ^4.1.1+1
  font_awesome_flutter: ^10.4.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre+1

  # Navigation and routing
  go_router: ^12.1.3
  page_transition: ^2.0.9

  # Networking and data
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

  # Firebase services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.9
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.3

  # Image handling
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  photo_view: ^0.14.0

  # Notifications
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2

  # Utilities
  intl: 0.20.2
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  in_app_review: ^2.0.6
  webview_flutter: ^4.4.2

  # Charts and data visualization
  fl_chart: ^0.66.0

  # Payments
  flutter_inapp_purchase: ^5.4.2
  stripe_payment: ^1.0.7

  # Social integration
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5

  # UI components
  carousel_slider: ^4.2.1
  expandable: ^5.0.1
  flutter_rating_bar: ^4.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.7.0
  dotted_border: ^2.1.0

  # Code quality and utilities
  collection: ^1.17.2
  async: ^2.11.0
  meta: ^1.10.0

  # Additional dependencies for FlutterFlow
  auto_size_text: ^3.0.0
  timeago: ^3.6.1
  json_path: ^0.7.2
  from_css_color: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Build and deployment
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/fonts/